name: clean_archi_flutter_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Service Locator
  get_it: ^7.4.1
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Value equality
  equatable: ^2.0.5
  # Functionnal programming thingies
  dartz: ^0.10.1
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.6
  # Local cache
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

